### ISSUE TITLE
peerDependencies deprecated; not fulfilled in npm 3+

### ISSUE THREAD

**Issue by glsignal** [KyleAMathews/react-autoupdate-time#1]
Warning received on installing your module

![screenshot from 2015-05-04 17-13-49](https://cloud.githubusercontent.com/assets/1109291/7449080/f76ecf52-f280-11e4-996a-a74a6e703652.png)

**Comment by KyleAMathews** [comment]
There's nothing to fix here. This is just NPM warning of a change in how it handles peerDependencies. From a module's perspective, nothing is changing. NPM is going to stop auto-installing peerDependencies and instead will warn you if the dependency (in this case, moment) is not installed.

**Comment by KyleAMathews** [comment]
See http://blog.npmjs.org/post/110924823920/npm-weekly-5

**Comment by glsignal** [comment]
:+1:
