### ISSUE TITLE
One setInterval to rule them all?

### ISSUE THREAD

**Issue by thom4parisot** [KyleAMathews/react-autoupdate-time#4]
Hi there,

I guess one interval timer is spun per component.
Is it reasonable to think we could have a way to have a mutual timer?

On a page with 200 items refreshed at the same time, there is no much point of having 200 timers but rather one which triggers 200 updates. Or not – if it's not performance compliant.

What do you think?

**Comment by KyleAMathews** [comment]
Sounds very sensible :-)

Could you put together a PR for this?
